# Generated by Django 4.2.3 on 2023-07-29 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created'], 'verbose_name': 'proyecto', 'verbose_name_plural': 'proyectos'},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='tittle',
            new_name='title',
        ),
    ]
